### ISSUE TITLE
Шапка

### ISSUE THREAD

**Issue by foxhable** [momo-hash1/kzgu#2]
- Выпадающее меню не готово или не работает?
- Элемент меню имеет активное состояние с синим цветом текста

![image](https://user-images.githubusercontent.com/36298346/227974158-e969750e-7048-40b8-a8fa-1e4e3e07a7f9.png)

- Кнопка “Оставить заявку” больше размером в макете

![image](https://user-images.githubusercontent.com/36298346/227974613-dc362dfc-09de-45e3-9759-0c6f8dcbb3a9.png)

- Элементы меню должны быть ссылками, а не `p` 
- Логотип должен быть ссылкой на главную
- Номер должен быть ссылкой типа 
```html
<a href="+71234567891">+7 (123) 456-78-91</a>
```
- Иконка лупы в поле поиска должна быть серого цвета

![image](https://user-images.githubusercontent.com/36298346/227977392-3c58e186-63e2-470d-80ec-39ea3bcab07a.png)

- Между элементами `.address` и `.leave-request`, расстояние больше, чем в макете

![image](https://user-images.githubusercontent.com/36298346/227977686-4d87f597-68af-4408-871b-518a02626122.png)

**Comment by momo-hash1** [comment]
Да меню еще не готово

**Comment by foxhable** [comment]
Как выполнишь правки - закрывай проблему. После я проверю, если что-то не так, то открою снова

**Comment by momo-hash1** [comment]
Поможешь с dropdown?

**Comment by foxhable** [comment]
Ссылка на телефон в макете `20px`, в верстке `22px`

![image](https://user-images.githubusercontent.com/36298346/229454078-80ce0eb4-3337-4249-bf2d-5dc0acce263a.png)

**Comment by foxhable** [comment]
Накинь на `.header-bottom` `align-items: center;`

![image](https://user-images.githubusercontent.com/36298346/229454849-03f598e2-ac23-45a1-9e39-6463964b0c7f.png)
